title: Tye Cameron-Robson
description: Robotics • Reinforcement Learning • Systems Engineering
url: https://tyecam1.github.io
theme: minima

# Show these pages in the top navigation
header_pages:
  - projects.md
  - blog/index.md
  - about.md

# Optional: author block
author:
  name: Tye Cameron-Robson
  email: tyecameron@hotmail.co.uk

# Markdown + plugins
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Clean blog URLs (optional)
permalink: /blog/:year/:month/:day/:title/
