title: Tye Cameron Portfolio
description: Software • Reinforcement Learning • Systems Engineering for Robotics
url: https://tyecam1.github.io
theme: minima

# Show these pages in the top navigation
header_pages:
  - projects.md
  - blog/index.md
  - about.md

# Markdown + plugins
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Clean blog URLs (optional)
permalink: /blog/:year/:month/:day/:title/
